### ISSUE TITLE
Missing binaries

### ISSUE THREAD

**Issue by its-luca** [FPSG-UIUC/augury#1]
Hi there,

first of all, nice paper and awesome that you open sourced your code.

After issuing `make` I tried to run the `./existence.sh` script and found that the underlying
`test_sweep.sh` script tries to call two binaries `./bin/i-test` and `./bin/a-test` that do not seem to exist.
Did I miss something here or where the binaries maybe renamed without adjusting the script?

Thanks

**Comment by jose-sv** [comment]
Thanks for the heads up, should be fixed now!
